import { playwright } from '@vitest/browser-playwright';
import { defineConfig } from 'vitest/config';

/**
 * Kernel tests run in a real browser against a real GPU. Node has no WebGPU, so there is
 * no meaningful unit test of a shader outside one — a mocked device would only test the
 * mock.
 *
 * `channel: 'chromium'` matters: Playwright's default headless build is the headless
 * shell, which has no GPU stack and reports no adapter. The flags enable WebGPU on
 * configurations where it is still gated.
 */
export default defineConfig({
  test: {
    browser: {
      enabled: true,
      headless: true,
      provider: playwright({
        launchOptions: {
          channel: 'chromium',
          args: ['--enable-unsafe-webgpu', '--enable-features=Vulkan'],
        },
      }),
      instances: [{ browser: 'chromium' }],
    },
    include: ['test/**/*.test.ts'],
    // Parity needs model.safetensors (942 MB) and reference.bin (44 MB), both gitignored and
    // both regenerated by tools/, so it is not part of the default suite. `npm run parity`
    // sets ENARGEIA_PARITY and gets it back.
    exclude: process.env.ENARGEIA_PARITY
      ? ['**/node_modules/**', '**/dist/**']
      : ['**/node_modules/**', '**/dist/**', 'test/parity/**'],
    // GPU work is slower to start than a pure-JS suite: device creation and the first
    // pipeline compile land in the first test that asks for them.
    testTimeout: 30_000,
    hookTimeout: 30_000,
  },
});
